version: '3'
services:
    frontend_alpine:
        entrypoint: ['yarn', 'start:docker']
        volumes:
            - ./app:/usr/app
        build:
            context: .
            dockerfile: Dockerfile_alpine
    
    frontend_buster:
        entrypoint: ['yarn', 'start:docker']
        volumes:
            - ./app:/usr/app
        build:
            context: .
            dockerfile: Dockerfile_buster

    frontend_stretch:
        entrypoint: ['yarn', 'start:docker']
        volumes:
            - ./app:/usr/app
        build:
            context: .
            dockerfile: Dockerfile_stretch

    frontend_stretch_slim:
        entrypoint: ['yarn', 'start:docker']
        volumes:
            - ./app:/usr/app
        build:
            context: .
            dockerfile: Dockerfile_stretch_slim
            
    nginx:
        image: nginx
        volumes:
            - ./nginx/templates:/etc/nginx/templates
        ports:
            - 9000:80
