version: '3'
services:
    frontend:
        entrypoint: ['yarn', 'start:docker']
        volumes:
            - ./app:/usr/app
        build:
            context: .
    nginx:
        image: nginx
        volumes:
            - ./nginx/templates:/etc/nginx/templates
        ports:
            - 9000:80
