version: '3'
services: 
    fronend:
        entrypoint: ['yarn', 'start:docker']
        volumes: 
            - ./app:/usr/app
        ports: 
            - 3000:3000
        build: 
            context: .
